# Generated by Django 2.0.1 on 2018-03-14 02:57

from django.db import migrations, models
import django.db.models.deletion
import fliermailses.methods


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cert_url', models.URLField(verbose_name='Certificate URL')),
                ('cert', models.TextField(blank=True, default=None, null=True, verbose_name='Certificate')),
            ],
            options={
                'verbose_name': 'SES Certificate',
                'verbose_name_plural': 'SES Certificate',
            },
            bases=(models.Model, fliermailses.methods.Certificate),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('message', models.TextField(help_text='SNS Message', verbose_name='SNS Message')),
                ('headers', models.TextField(blank=True, default='', help_text='SNS Headers Help', null=True, verbose_name='SNS Headers')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notification',
            },
            bases=(models.Model, fliermailses.methods.Notification),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(help_text='Service Name Help', max_length=100, verbose_name='Service Name')),
                ('region', models.CharField(blank=True, default=None, help_text='SES Region Help', max_length=30, null=True, verbose_name='SES Region')),
                ('key', models.CharField(blank=True, default=None, help_text='SES Access Key Help', max_length=100, null=True, verbose_name='SES Access Key')),
                ('secret', models.CharField(blank=True, default=None, help_text='SES Access Secret Help', max_length=100, null=True, verbose_name='SES Access Secret')),
                ('settings', models.TextField(blank=True, default=None, null=True, verbose_name='Settings')),
            ],
            options={
                'verbose_name': 'SES Service',
                'verbose_name_plural': 'SES Service',
            },
            bases=(models.Model, fliermailses.methods.Service),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(help_text='Sender Name Help', max_length=100, verbose_name='Sender Name')),
                ('address', models.EmailField(max_length=100, verbose_name='Sender Address')),
                ('arn', models.CharField(blank=True, default=None, help_text='Source Identity Arn Help', max_length=100, null=True, verbose_name='Source Identity Arn')),
                ('service', models.ForeignKey(blank=True, default=None, help_text='Service Help', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fliermailses.Service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'SES Source',
                'verbose_name_plural': 'SES Source',
            },
            bases=(models.Model, fliermailses.methods.Source),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('topic', models.IntegerField(choices=[(0, 'Bounce Topic'), (1, 'Complaint Topic'), (2, 'Delivery Topic')], default=0, verbose_name='Topic')),
                ('arn', models.CharField(blank=True, default=None, help_text='Topic Arn Help', max_length=100, null=True, verbose_name='Topic Arn')),
                ('source', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fliermailses.Source')),
            ],
            options={
                'verbose_name': 'SNS Topic',
                'verbose_name_plural': 'SNS Topic',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='topic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fliermailses.Topic'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fliermailses.Service'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('source', 'topic')},
        ),
    ]
